name: Build Kibana app & release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: fastlorenzo/redelk-kibana-app
        path: ./plugin
    - name: Get Kibana version
      id: set_var
      run: |
        content=`cat ./redelk/kibana.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=kibanaJson::$content"
    - uses: actions/checkout@master
      with:
        repository: elastic/kibana
        path: ./kibana
        ref: "v${{fromJson(steps.set_var.outputs.kibanaJson).version}}"
    - name: Read .nvmrc
      run: NVMRC=$(cat ./kibana/.nvmrc)
      id: nvm
    - name: Move plugin to Kibana directory
      run: |
        mv ./plugin ./kibana/plugins/${{fromJson(steps.set_var.outputs.kibanaJson).id}}
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./kibana/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./kibana/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Bootstrap Kibana
      run: cd ./kibana/plugins/redelk && yarn kbn bootstrap
    - name: Fix redux-toolkit
      run: sed -i 's/^const /^let /g' ./kibana/plugins/redelk/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js
#    - name: Run optimizer manually (https://github.com/elastic/kibana/issues/70426)
#      run: cd ./kibana/plugins/redelk && node ../../scripts/build_kibana_platform_plugins --verbose --no-examples --dist --filter redelk
    - name: Build RedELK plugin
      run: cd ./kibana/plugins/redelk && yarn build --skip-archive && mkdir build/kibana/redelk/public && cp -R public/assets/ build/kibana/redelk/public && cd build && zip redelk-7.10.0.zip kibana -r
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: plugin-zip
        path: |
          ./kibana/plugins/redelk/build/*.zip
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./kibana/plugins/redelk/build/*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
